apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: tech-trends
    tag: web
  name: tech-trends-web
  namespace: {{ .Values.namespace.name }} 
spec:
  replicas: {{ .Values.replicaCount }} 
  selector:
    matchLabels:
      app: tech-trends
      tag: web
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: tech-trends
        tag: web
    spec:
      containers:
      - image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        name: tech-trends
        livenessProbe:
          httpGet:
            path: /status/healthcheck
            port: 3111
          initialDelaySeconds: 15
          timeoutSeconds: 10
        readinessProbe:
          httpGet:
            path: /status/healthcheck
            port: 3111
          initialDelaySeconds: 10
          timeoutSeconds: 10
        lifecycle:
          postStart:
            exec:
              command: ["python", "init_db.py"]
        volumeMounts:
        - mountPath: /app/database.db
          name: sqlitedb
      volumes:
      - name: sqlitedb
        hostPath:
          path: {{ .Values.hostPath.hostPathName }}
          type: FileOrCreate

        resources:
{{ toYaml .Values.resources | indent 12 }}
