apiVersion: v1
kind: Service
metadata:
  name: tech-trends-service
  namespace: {{ .Values.namespace.name }}
  labels:
    app: tech-trends
    tag: web
spec:
  ports:
  - name: http
    port: 3111
    protocol: TCP
    targetPort: 3111
    nodePort: 30020
  - name: https
    port: 443
    protocol: TCP
    targetPort: 3111s
    nodePort: 30021
  selector:
    app: tech-trends
  sessionAffinity: None
  type: NodePort
