namespace:
  name: staging

service:
  nodePortHttp: 30030 
  nodePortHttps: 30031

image:
  repository: oyelowo/tech-trends-app
  tag: latest
  pullPolicy: IfNotPresent

replicaCount: 2

resources:
  requests:
    cpu: 45m
    memory: 256Mi

hostPath:
  path: /mnt/data/staging/database.db
