namespace:
  name: development
service:
  nodePortHttp: 30020
  nodePortHttps: 30021
image:
  repository: oyelowo/techtrends
  tag: "master-b5af6a822f0b900f6fd65de1e4460ec62e50e7ac"
  pullPolicy: IfNotPresent
replicaCount: 2
resources:
  requests:
    cpu: 50m
    memory: 256Mi
hostPath:
  path: /mnt/data/development/database.db
