name: Tech trends

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  IMAGE: tech-trends
  IMAGE_WITH_TAG: ${{ secrets.DOCKERHUB_USERNAME }}/$IMAGE:${GITHUB_REF#refs/heads/}-$GITHUB_SHA

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Create image name and tag
        run: | 
         echo "IMAGE_WITH_TAG=${{ secrets.DOCKERHUB_USERNAME }}/$IMAGE:${GITHUB_REF#refs/heads/}-$GITHUB_SHA" >> $GITHUB_ENV
         echo ${{env.IMAGE_WITH_TAG}}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      
      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64
          push: true
          tags: ${{env.IMAGE_WITH_TAG}}

  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Create image name and tag
      run: echo "$GITHUB_SHA"

    - name: Setup Kustomize
      uses: imranismail/setup-kustomize@v1
      with:
        kustomize-version: "3.8.7"

    - name: Update Kubernetes resources
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      run: |
       cd kustomize/tech-trends/base
       kustomize edit set image oyelowo/tech-trends=${{env.IMAGE_WITH_TAG}}
       cat kustomization.yaml
        
    - name: Commit files
      run: |
        git config --local user.email "oyelowooyedayo@gmail.com"
        git config --local user.name "GitHub Action"
        git commit -am "Bump docker tag"

    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
